### PR TITLE
Add GHA

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #1

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse as I see CI works, but there is some missing dependency or something wrong with tex files

```
Error:undefined:\section The token T_CS[\section] is not defined.
	at 00-foreword.tex; line 1 col 8 - line 1 col 8
	Defining it now as <ltx:ERROR/>
	In Core::Stomach[@0x7fbe9485de30] /Users/runner/runners/2.165.2/work/mn-samples-tex-iso/mn-samples-tex-iso/sections-en/00-foreword.tex; from line 1 col 8 to line 1 col 8

Error:undefined:\get The token T_CS[\get] is not defined.
	at 00-foreword.tex; line 15 col 61 - line 15 col 61
	Defining it now as <ltx:ERROR/>
	In Core::Stomach[@0x7fbe9485de30] /Users/runner/runners/2.165.2/work/mn-samples-tex-iso/mn-samples-tex-iso/sections-en/00-foreword.tex; from line 15 col 61 to line 15 col 61

Error:undefined:\textit The token T_CS[\textit] is not defined.
	at 00-foreword.tex; line 15 col 98 - line 15 col 98
	Defining it now as <ltx:ERROR/>
	In Core::Stomach[@0x7fbe9485de30] /Users/runner/runners/2.165.2/work/mn-samples-tex-iso/mn-samples-tex-iso/sections-en/00-foreword.tex; from line 15 col 98 to line 15 col 98
```

**Comment by CAMOBAP** [comment]
Can it be related to the wrong version of latexml and we need to use `cpanm --notest git://github.com/brucemiller/LaTeXML.git@9a0e7dc5` ?

**Comment by CAMOBAP** [comment]
OSX & Windows fixed after moving to a version from master branch

But for ubuntu issue still exists

```
Fatal:I/O:open Can't open /home/runner/work/mn-samples-tex-iso/mn-samples-tex-iso/sections-en/b0-bibliography.tex for reading
	at b0-bibliography.tex
	Permission denied
	Stack Trace:
		Mouth[/home/runner/work/mn-samples-te...->openFile('/home/runner/work/mn-samples-tex-iso...) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core/Mouth/file.pm line 27
	LaTeXML::Core::Mouth::file::new('LaTeXML::Core::Mouth::file','/home/runner/work/mn-samples-tex-iso...,'notes',1,'content',undef) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core/Mouth.pm line 48
	LaTeXML::Core::Mouth::create('LaTeXML::Core::Mouth','/home/runner/work/mn-samples-tex-iso...,'notes',1,'content',undef) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Package.pm line 1994
	LaTeXML::Package::loadTeXContent('/home/runner/work/mn-samples-tex-iso...) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Package.pm line 1853
	LaTeXML::Package::InputContent('/home/runner/work/mn-samples-tex-iso...) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core.pm line 148
	LaTeXML::Core::__ANON__(LaTeXML::Core::State=HASH(0x49bc638)) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core.pm line 245
	Core[@0x4c2aa68]->withState(CODE(0x4c2abe8)) @ /snap/latexml/15/usr/local/share/perl/5.22.1/LaTeXML/Core.pm line 157
	Core[@0x4c2aa68]->digestFile('sections-en/b0-bibliography.tex','mode','TeX','preamble',undef,'postamble',undef) @ /snap/latexml/15/usr/local/bin/latexml line 103
	eval {...} @ /snap/latexml/15/usr/local/bin/latexml line 98
```

**Comment by ronaldtse** [comment]
@CAMOBAP795 the `tex` files should not be executable. Can you please keep them as 644? Thanks.

**Comment by CAMOBAP** [comment]
> the tex files should not be executable. Can you please keep them as 644? Thanks.

@ronaldtse,  Done

BTW, The issue with snap, reporting https://github.com/metanorma/latexml-snap/issues/12

**Pull request merged**
